version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgresDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: hostels-nearmeDB
    volumes:
      - ./db-docker:/var/lib/postgresql/data  # Use relative path for better compatibility
    restart: always
