version: "3.8"

services:
  nextjs:
    image: zeusnotfound/hostelsnearme:latest
    container_name: hostels-nearme-nextjs
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      NODE_ENV: production
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
