import type { Metadata } from "next";
import SessionProviderWrapper from "./SessionProviderWrapper"; // Import the wrapper
import "./globals.css";
import Navbar from "@/components/Navbar";
import Container from "@/components/Container";
import { Toaster } from "@/components/ui/toaster"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className=""
      >
        <SessionProviderWrapper>
          <Navbar/>
            <Container>
              {children} 
              <Toaster/>
            </Container>
          </SessionProviderWrapper>
      </body>
    </html>
  );
}
