import type { Metadata } from "next";
import SessionProviderWrapper from "../components/providers/SessionProviderWrapper"; // Import the Session Provider
import ReactQueryProvider from "../components/providers/ReactQueryProvider"; // Import the React Query Provider
import "./globals.css";
import Navbar from "@/components/Navbar";
import Container from "@/components/ui/Container";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          <ReactQueryProvider>
            <Navbar />
            <Container>
              {children}
              <Toaster />
            </Container>
          </ReactQueryProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
